# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PursuitGramProj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PursuitGramProj
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
	
  target 'PursuitGramProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
